title: Greenhouse changes, everything
author: BrookLeigh
email: brook.vandenbrink@elastic.co
description: > # this means to ignore newlines until "baseurl:"
  So... I've been thinking.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
